version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  transcoding-controller:
    build:
      context: ./transcoding-controller
    image: transcoding-controller:latest
    container_name: transcoding-controller
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: kafka:9092
      SQLITE_DB_PATH: /app/db/data/jobs.db   # ✅ for DB query endpoint
    depends_on:
      - kafka
      - redis
    volumes:
      - db-data:/app/db/data                 # ✅ required for reading DB
    restart: unless-stopped
    tty: true

  transcode-worker:
    build:
      context: ./transcode-worker
    image: transcode-worker:latest
    container_name: transcode-worker
    environment:
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
      - redis
    volumes:
      - segments-data:/segments
    restart: unless-stopped
    tty: true

  tracker:
    build:
      context: ./tracker
    image: tracker:latest
    container_name: tracker
    environment:
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
      - redis
    restart: unless-stopped
    tty: true

  mpd-generator:
    build:
      context: ./mpd-generator
    image: mpd-generator:latest
    container_name: mpd-generator
    environment:
      REDIS_ADDR: redis:6379
      KAFKA_BROKER: kafka:9092
      SQLITE_DB_PATH: /app/db/data/jobs.db
      PUBLIC_HOST: http://13.57.143.121
    depends_on:
      - kafka
      - redis
    volumes:
      - segments-data:/segments   # ✅ shared transcoded files
      - db-data:/app/db/data      # ✅ SQLite DB directory
    restart: unless-stopped
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - segments-data:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  segments-data:
  db-data:
