  transcoding-controller:
    image: transcoding-controller:latest  # 👈 Use local image name
    container_name: transcoding-controller
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
      - redis
